export const NIGERIAN_UNIVERSITIES = [
    "Abia State University",
    "Achievers University, Owo",
    "Adamawa State University",
    "Adekunle Ajasin University",
    "Adeleke University",
    "Admiralty University of Nigeria",
    "Afe Babalola University",
    "African University of Science and Technology",
    "Ahmadu Bello University",
    "Ajayi Crowther University",
    "Akwa Ibom State University",
    "Alex Ekwueme Federal University, Ndufu-Alike",
    "Al-Hikmah University",
    "Al-Qalam University, Katsina",
    "Ambrose Alli University",
    "American University of Nigeria",
    "Anchor University, Lagos",
    "Arthur Jarvis University",
    "Atiba University",
    "Augustine University",
    "Babcock University",
    "Bauchi State University",
    "Bayero University Kano",
    "Baze University",
    "Bells University of Technology",
    "Benson Idahosa University",
    "Benue State University",
    "Bingham University",
    "Borno State University",
    "Bowen University",
    "Buka Abba Ibrahim University",
    "Caleb University",
    "Caritas University",
    "Chrisland University",
    "Christopher University",
    "Chukwuemeka Odumegwu Ojukwu University",
    "Clifford University",
    "Coal City University",
    "Covenant University",
    "Crawford University",
    "Crescent University, Abeokuta",
    "Cross River University of Technology",
    "Crown Hill University",
    "Delta State University, Abraka",
    "Dominican University, Ibadan",
    "Eastern Palm University",
    "Ebonyi State University",
    "Edo University",
    "Edwin Clark University",
    "Ekiti State University, Ado Ekiti",
    "Eko University of Medicine and Health Sciences",
    "Elizade University",
    "Enugu State University of Science and Technology",
    "Evangel University, Akaeze",
    "Federal University of Agriculture, Abeokuta",
    "Federal University of Petroleum Resources",
    "Federal University of Technology, Akure",
    "Federal University of Technology, Minna",
    "Federal University of Technology, Owerri",
    "Federal University, Birnin Kebbi",
    "Federal University, Dutse",
    "Federal University, Dutsin-Ma",
    "Federal University, Gashua",
    "Federal University, Gusau",
    "Federal University, Kashere",
    "Federal University, Lafia",
    "Federal University, Lokoja",
    "Federal University, Otuoke",
    "Federal University, Oye-Ekiti",
    "Federal University, Wukari",
    "Fountain University, Osogbo",
    "Gombe State University",
    "G Gregory University, Uturu",
    "Hallmark University",
    "Hezekiah University",
    "Ibrahim Badamasi Babangida University",
    "Igbinedion University Okada",
    "Ignatius Ajuru University of Education",
    "Imo State University",
    "Joseph Ayo Babalola University",
    "Kaduna State University",
    "Kano University of Science and Technology",
    "Kebbi State University of Science and Technology",
    "Kings University",
    "Kogi State University",
    "Kola Daisi University",
    "Kwara State University",
    "Kwararafa University, Wukari",
    "Ladoke Akintola University of Technology",
    "Lagos State University",
    "Landmark University",
    "Lead City University",
    "Legacy University, Okija",
    "Madonna University, Nigeria",
    "Mcpherson University",
    "Michael and Cecilia Ibru University",
    "Michael Okpara University of Agriculture",
    "Modibbo Adama University of Technology",
    "Mountain Top University",
    "Nasarawa State University",
    "Niger Delta University",
    "Nile University of Nigeria",
    "Nnamdi Azikiwe University",
    "Novena University",
    "Obafemi Awolowo University",
    "Obong University",
    "Oduduwa University",
    "Olabisi Onabanjo University",
    "Ondo State University of Science and Technology",
    "Osun State University",
    "Pan-Atlantic University",
    "Paul University",
    "Plateau State University",
    "PAMO University of Medical Sciences",
    "Precious Cornerstone University",
    "Redeemer's University",
    "Renaissance University",
    "Rhema University",
    "Ritman University",
    "Rivers State University",
    "Salem University",
    "Samuel Adegboyega University",
    "Skyline University Nigeria",
    "Sokoto State University",
    "Southwestern University, Nigeria",
    "Spiritan University, Nneochi",
    "Summit University, Offa",
    "Tai Solarin University of Education",
    "Tansian University",
    "Taraba State University",
    "The Technical University",
    "Umaru Musa Yar'adua University",
    "University of Abuja",
    "University of Africa, Toru-Orua",
    "University of Agriculture, Makurdi",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Medical Sciences",
    "University of Mkar",
    "University of Nigeria",
    "University of Port Harcourt",
    "University of Uyo",
    "Usmanu Danfodiyo University",
    "Veritas University",
    "Wellspring University",
    "Wesley University of Science and Technology",
    "Western Delta University",
    "Yobe State University",

    // Federal Polytechnics
    "Akanu Ibiam Federal Polytechnic, Unwana",
    "Air Force Institute of Technology, Kaduna",
    "Auchi Polytechnic",
    "Federal Polytechnic, Ado-Ekiti",
    "Federal Polytechnic, Ayede",
    "Federal Polytechnic, Bali",
    "Federal Polytechnic, Bauchi",
    "Federal Polytechnic, Bida",
    "Federal Polytechnic, Damaturu",
    "Federal Polytechnic, Daura",
    "Federal Polytechnic, Ede",
    "Federal Polytechnic, Ekowe",
    "Federal Polytechnic, Idah",
    "Federal Polytechnic, Ilaro",
    "Federal Polytechnic, Ile-Oluji",
    "Federal Polytechnic, Kaura Namoda",
    "Federal Polytechnic, Mubi",
    "Federal Polytechnic, Nasarawa",
    "Federal Polytechnic, Nekede",
    "Federal Polytechnic, Offa",
    "Federal Polytechnic, Oko",
    "Federal Polytechnic, Ugep",
    "Hussaini Adamu Federal Polytechnic, Kazaure",
    "Kaduna Polytechnic",
    "Waziri Umaru Federal Polytechnic, Birnin Kebbi",
    "Yaba College of Technology",

    // State Polytechnics
    "Abdu Gusau Polytechnic, Talata Mafara",
    "Abia State Polytechnic, Aba",
    "Abraham Adesanya Polytechnic, Ijebu-Igbo",
    "Abubakar Tatari Ali Polytechnic, Bauchi",
    "Adamawa State Polytechnic, Yola",
    "Adeseun Ogundoyin Polytechnic, Eruwa",
    "Akwa Ibom State Polytechnic, Ikot Osurua",
    "Anambra State Polytechnic, Mgbakwu",
    "Bayelsa State Polytechnic, Aleibiri",
    "Benue State Polytechnic, Ugbokolo",
    "Binyaminu Usman Polytechnic, Hadejia",
    "Delta State Polytechnic, Ogwashi-Uku",
    "Delta State Polytechnic, Otefe-Oghara",
    "Delta State Polytechnic, Ozoro",
    "D.S. Adegbenro ICT Polytechnic, Itori-Ewekoro",
    "Edo State Polytechnic, Usen",
    "Enugu State Polytechnic, Iwollo",
    "Gateway Polytechnic, Igbesa",
    "Gateway Polytechnic, Saapade",
    "Hassan Usman Katsina Polytechnic, Katsina",
    "Institute of Management and Technology, Enugu",
    "Jigawa State Polytechnic, Dutse",
    "Kano State Polytechnic",
    "Ken Saro-Wiwa Polytechnic, Bori",
    "Kogi State Polytechnic, Lokoja",
    "Kwara State Polytechnic, Ilorin",
    "Lagos State Polytechnic, Ikorodu",
    "Mai-Idris Alooma Polytechnic, Geidam",
    "Moshood Abiola Polytechnic, Abeokuta",
    "Niger State Polytechnic, Zungeru",
    "Nuhu Bamalli Polytechnic, Zaria",
    "Osun State College of Technology, Esa-Oke",
    "Osun State Polytechnic, Iree",
    "Plateau State Polytechnic, Barkin-Ladi",
    "Port Harcourt Polytechnic",
    "Ramat Polytechnic, Maiduguri",
    "Rivers State Polytechnic, Bori",
    "Rufus Giwa Polytechnic, Owo",
    "The Polytechnic, Ibadan",
    "Yobe State Polytechnic, Damaturu",

    // Private Polytechnics
    "Ajayi Polytechnic, Ikere Ekiti",
    "Al-Hikma Polytechnic, Karu",
    "Allover Central Polytechnic, Sango Ota",
    "Ashi Polytechnic, Anyiin",
    "Bellarks Polytechnic, Kwale",
    "Best Solution Polytechnic, Akure",
    "Bolmor Polytechnic, Ibadan",
    "Brainfill Polytechnic, Ikot Ekpene",
    "Calvary Polytechnic, Owa-Oyibu",
    "Citi Polytechnic, Abuja",
    "Coastal Polytechnic, Apapa",
    "Covenant Polytechnic, Aba",
    "Crown Polytechnic, Ado-Ekiti",
    "Dorben Polytechnic, Bwari",
    "Eastern Polytechnic, Port Harcourt",
    "Fidei Polytechnic, Gboko",
    "Foundation College of Technology, Ikot Ekpene",
    "Grace Polytechnic, Surulere",
    "Heritage Polytechnic, Eket",
    "Igbajo Polytechnic, Igbajo",
    "Kalac Christal Polytechnic, Lekki",
    "Kings Polytechnic",
    "Lagos City Polytechnic, Ikeja",
    "Lighthouse Polytechnic",
    "Our Saviour Institute of Science, Agriculture & Technology, Enugu",
    "Prime Polytechnic, Ajaokuta",
    "Ronik Polytechnic, Ejigbo",
    "Saf Polytechnic, Iseyin",
    "Southern Atlantic Polytechnic, Uyo",
    "Speedway Polytechnic, Ojudu",
    "Temple Gate Polytechnic, Aba",
    "The Polytechnic, Ile-Ife",
    "Tower Polytechnic, Ibadan",
    "Wolex Polytechnic, Iwo",
].sort();
